CREATE SEQUENCE  "REPORT_MGR"."HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20 NOORDER  NOCYCLE ;

CREATE TABLE "REPORT_MGR"."REPORT" 
(
"ID" NUMBER(14,0), 
"NAME" VARCHAR2(200 BYTE), 
"DESCRIPTION" VARCHAR2(4000 BYTE), 
"VERSION" NUMBER(14,0), 
"BUSINESS_UNIT" VARCHAR2(100 BYTE), 
"PURPOSE" VARCHAR2(100 BYTE), 
"ROLE" VARCHAR2(100 BYTE), 
"TYPE" VARCHAR2(100 BYTE), 
"FREQUENCY" VARCHAR2(200 BYTE), 
"TEMPLATE" BLOB, 
"OUTPUT_FORMAT" VARCHAR2(100 BYTE), 
"OUTPUT_PROTOCOL" VARCHAR2(100 BYTE), 
"OUTPUT_LOCATION" VARCHAR2(4000 BYTE), 
"INPUT_LOCATION" VARCHAR2(4000 BYTE), 
"ETL_TOOL" VARCHAR2(100 BYTE), 
"ETL_SCRIPT" BLOB, 
"CREATED_DATE" TIMESTAMP (6), 
"CREATED_BY" NUMBER(14,0), 
"ACTIVE" CHAR(1 BYTE)
);
 

COMMENT ON COLUMN "REPORT_MGR"."REPORT"."PURPOSE" IS 'Internal, External';
COMMENT ON COLUMN "REPORT_MGR"."REPORT"."TYPE" IS 'Manual,Schedule';
COMMENT ON COLUMN "REPORT_MGR"."REPORT"."OUTPUT_FORMAT" IS 'PDF, RTF, CSV, HTML';
COMMENT ON COLUMN "REPORT_MGR"."REPORT"."OUTPUT_PROTOCOL" IS 'FTP, HTTP, Email';
COMMENT ON COLUMN "REPORT_MGR"."REPORT"."OUTPUT_LOCATION" IS 'Location where the output file should be saved';
COMMENT ON COLUMN "REPORT_MGR"."REPORT"."INPUT_LOCATION" IS 'Source location of report';
COMMENT ON COLUMN "REPORT_MGR"."REPORT"."ACTIVE" IS '0 or 1';

